name: earthquake-prediction
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch

dependencies:
  # Python Version
  - python=3.9

  # Core Scientific Computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0

  # Machine Learning and Deep Learning
  - tensorflow>=2.7.0
  - keras
  - scikit-learn>=0.24.0
  - pytorch
  - torchvision
  - torchaudio

  # Time Series Analysis
  - statsmodels
  - pmdarima

  # Data Visualization
  - matplotlib
  - seaborn
  - plotly
  - bokeh

  # Geospatial Analysis
  - geopandas
  - folium
  - shapely

  # Additional Utilities
  - tqdm
  - joblib

  # Development and Notebook Environment
  - jupyter
  - jupyterlab
  - ipykernel

  # GPU Support (optional)
  - cudatoolkit
  - cudnn

  # Optional Advanced Libraries
  - prophet

  # Pip installable packages (for libraries not in conda)
  - pip
  - pip:
    - tensorflow-addons
    - tensorflow-probability
    - git+https://github.com/tensorflow/addons.git  # Latest TF Addons
    - optuna  # Hyperparameter optimization
    - ray[tune]  # Distributed computing
    - wandb  # Experiment tracking

  # Development and Testing
  - pytest
  - pylint
  - black  # Code formatting

# Post-install script (optional)
variables:
  PYTHONPATH: '.'